### Register User
POST http://localhost:9090/api/users/register
Content-Type: application/json

{
  "username": "rahul",
  "password": "a",
  "email": "rahul@gmail.com",
  "name": "rahul"
}

###
### Login User
POST http://localhost:9090/api/users/login
Content-Type: application/json

{
  "email": "rahul@gmail.com",
  "password": "a"
}

###
### Get User Profile
GET http://localhost:9090/api/users/get_user_profile
token: 5412f36938ab01436dc195d79bdc43189f57f4ede262aa07e37fd2632919b1dd

###
### Get All Users
GET http://localhost:9090/api/users/get_all_users
###